enum Icon {
  ChannelStagePrivateActive = 'https://cdn3.emoji.gg/emojis/6301-channel-stage-private-active.png',
  ChannelCategoryCollapsed = 'https://cdn3.emoji.gg/emojis/3981-channel-category-collapsed.png',
  ChannelForumPrivate = 'https://cdn3.emoji.gg/emojis/7302-channel-forum-private.png',
  ChannelVoicePrivate = 'https://cdn3.emoji.gg/emojis/4650-channel-voice-private.png',
  ChannelStagePrivate = 'https://cdn3.emoji.gg/emojis/5773-channel-stage-private.png',
  ChannelTextPrivate = 'https://cdn3.emoji.gg/emojis/8336-channel-text-private.png',
  ChannelStageActive = 'https://cdn3.emoji.gg/emojis/2698-channel-stage-active.png',
  ChannelNewsPrivate = 'https://cdn3.emoji.gg/emojis/5979-channel-news-private.png',
  ChannelVoiceNSFW = 'https://cdn3.emoji.gg/emojis/6322-channel-voice-nsfw.png',
  ChannelForumNSFW = 'https://cdn3.emoji.gg/emojis/5539-channel-forum-nsfw.png',
  ChannelForumPost = 'https://cdn3.emoji.gg/emojis/3977-channel-forum-post.png',
  ChannelNewsNSFW = 'https://cdn3.emoji.gg/emojis/7684-channel-news-nsfw.png',
  ChannelTextNSFW = 'https://cdn3.emoji.gg/emojis/1927-channel-text-nsfw.png',
  ChannelCategory = 'https://cdn3.emoji.gg/emojis/9245-channel-category.png',
  BadgeNewMember = 'https://cdn3.emoji.gg/emojis/7849-badge-new-member.png',
  ChannelPrivate = 'https://cdn3.emoji.gg/emojis/9245-channel-private.png',
  SuperReaction = 'https://cdn3.emoji.gg/emojis/7119-super-reaction.png',
  SilentMessage = 'https://cdn3.emoji.gg/emojis/6957-silent-message.png',
  ReportMessage = 'https://cdn3.emoji.gg/emojis/3392-report-message.png',
  DeleteMessage = 'https://cdn3.emoji.gg/emojis/3656-delete-message.png',
  ChannelThread = 'https://cdn3.emoji.gg/emojis/4068-channel-thread.png',
  ChannelBrowse = 'https://cdn3.emoji.gg/emojis/1780-channel-browse.png',
  ChannelForum = 'https://cdn3.emoji.gg/emojis/1780-channel-forum.png',
  ChannelVoice = 'https://cdn3.emoji.gg/emojis/6322-channel-voice.png',
  ChannelStage = 'https://cdn3.emoji.gg/emojis/6528-channel-stage.png',
  ChannelRules = 'https://cdn3.emoji.gg/emojis/6127-channel-rules.png',
  ChannelNews = 'https://cdn3.emoji.gg/emojis/8176-channel-news.png',
  ChannelText = 'https://cdn3.emoji.gg/emojis/6139-channel-text.png',
  EditMessage = 'https://cdn3.emoji.gg/emojis/7574-edit-message.png',
  TTSMessage = 'https://cdn3.emoji.gg/emojis/1040-tts-message.png',
  MarkUnread = 'https://cdn3.emoji.gg/emojis/4989-mark-unread.png',
  ServerDeaf = 'https://cdn3.emoji.gg/emojis/3595-server-deaf.png',
  BadgeOwner = 'https://cdn3.emoji.gg/emojis/3199-badge-owner.png',
  PinMessage = 'https://cdn3.emoji.gg/emojis/8004-pin-message.png',
  ServerMute = 'https://cdn3.emoji.gg/emojis/8598-server-mute.png',
  CopyLink = 'https://cdn3.emoji.gg/emojis/2988-copy-link.png',
  CopyText = 'https://cdn3.emoji.gg/emojis/2009-copy-text.png',
  SelfDeaf = 'https://cdn3.emoji.gg/emojis/9823-self-deaf.png',
  SelfMute = 'https://cdn3.emoji.gg/emojis/1129-self-mute.png',
  Reaction = 'https://cdn3.emoji.gg/emojis/4901-reaction.png',
  CopyID = 'https://cdn3.emoji.gg/emojis/8254-copy-id.png',
  Undeaf = 'https://cdn3.emoji.gg/emojis/1843-undeaf.png',
  Unmute = 'https://cdn3.emoji.gg/emojis/6859-unmute.png',
  Reply = 'https://cdn3.emoji.gg/emojis/1932-reply.png',

  EmojiCash = '<:cash:1223716699216281706>',
  EmojiCoins = '<:coins:1223716653712539680>',
  EmojiGoldBar = '<:goldbar:1223716675166146673>',
  EmojiOpenTreasureChest = '<:opentreasurechest:1223716688126546091>',
  EmojiReceiveMoney = '<:receivemoney:1223716632460005498>',
  EmojiRollingDices = '<:rollingdices:1223716578319794176>',
  EmojiSnatch = '<:snatch:1223716605528379464>',

  Cash = 'cash.png',
  Coins = 'coins.png',
  GoldBar = 'gold-bar.png',
  OpenTreasureChest = 'open-treasure-chest.png',
  ReceiveMoney = 'receive-money.png',
  RollingDices = 'rolling-dices.png',

  DiceOne = 'dice-one.png',
  DiceTwo = 'dice-two.png',
  DiceThree = 'dice-three.png',
  DiceFour = 'dice-four.png',
  DiceFive = 'dice-five.png',
  DiceSix = 'dice-six.png',

  Snatch = 'snatch.png',
  PiggyBank = 'piggy-bank.png',
  Amputation = 'amputation.png',
  Robber = 'robber.png',

  TemporaryShield = 'temporary-shield.png',
  ShieldDisabled = 'shield-disabled.png',

  HazardSign = 'hazard-sign.png',

  Podium = 'podium.png',
}

export default Icon
